deligran-rest:
  config:
    # THIS_FILE or CONFIG_SERVER
    type: THIS_FILE
  server:
    port: 8081
    # IPV4, IPV6 or ALL
    network-type: IPV4
    # HTTP or HTTPS
    protocol: HTTPS
    root-ca-private-key:
      -----BEGIN ENCRYPTED PRIVATE KEY-----
      .
      .
      .
      -----END ENCRYPTED PRIVATE KEY-----
    root-ca-private-key-password: password
    root-ca-certificate:
      -----BEGIN CERTIFICATE-----
      .
      .
      .
      -----END CERTIFICATE-----
  application:
    # "type-channel-name-version" used for name base path and file log
    type: business
    channel: sales
    name: products
    version: v1
    description:
      Inicios de DeliGran REST C Framework

deligran-utils-log:
  config:
    # CONSOLE, FILE or CONSOLE_AND_FILE
    type: CONSOLE_AND_FILE
    level: ALL
    # format sys/time was added %MCS = Microseconds and %MLS = Milliseconds
    format-date-time: "%d/%m/%Y %H:%M:%S.%MCS"
    file:
      path: /path/to/log/file