deligran-rest: 
  config: 
    # THIS_FILE or CONFIG_SERVER
    type: THIS_FILE
  server: 
    # number of cores in your system
    thread-poll-size: 4
    # IPV4, IPV6 or ALL
    network-type: IPV6
    port: 8081
    # HTTP or HTTPS
    protocol: HTTP
    root-ca-private-key: 
    root-ca-private-key-password: 
    root-ca-certificate: 
  application: 
    # Base path "type-channel-name-version" used for name base path and file log, otherwise custom-name is used
    type: 
    channel: 
    name: 
    version: 
    description: 
      Description for TestDGR
    # Replace base path
    custom-name: testdgr
deligran-utils-log: 
  config: 
    # CONSOLE, FILE or CONSOLE_AND_FILE
    type: CONSOLE_AND_FILE
    level: ALL
    # format sys/time was added %MCS = Microseconds and %MLS = Milliseconds
    format-date-time: "%d/%m/%Y %H:%M:%S.%MCS"
    file: 
      path: /var/tmp
      max-size: 20M
      max-count: 20
deligran-db: 
  # YAML/JSON file used at runtime, it is used to create the header file with DeliGranCli option --database or -db
  path-file-databases: 
  data-sources: 
  #- data-source: 
      #name: 
      # PostgreSQL, MySQL, MariaDB, SQLite, Redis, MongoDB, MSSqlServer
      #driver: 
      # URI driver
      #uri: 
